apiVersion: v1
kind: Service
metadata:
  name: portfolio
  namespace: stefansportfolio
spec:
  selector:
    app: portfolio
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31056
  type: NodePort
