apiVersion: v1
kind: ConfigMap
metadata:
  name: dns-config
  namespace: stefansportfolio
data:
  resolv.conf: |
    nameserver 1.1.1.1
    nameserver 1.0.0.1
    nameserver 8.8.8.8
    nameserver 8.8.4.4
    options ndots:2 edns0
