apiVersion: apps/v1
kind: Deployment
metadata:
  name: traceroute-backend
  namespace: stefansportfolio
  labels:
    app: traceroute-backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: traceroute-backend
  template:
    metadata:
      labels:
        app: traceroute-backend
    spec:
      containers:
      - name: traceroute-backend
        image: stefanmhall/traceroute-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: websocket
        env:
        - name: CORS_ORIGIN
          value: "*"
        - name: GIN_MODE
          value: "release"
        - name: SOCKET_IO_ENABLED
          value: "true"
        - name: WEBSOCKET_ENABLED
          value: "true"
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        # Security context - traceroute requires root privileges
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - NET_RAW
            - NET_ADMIN
        startupProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
          readOnly: true
      volumes:
      - name: timezone
        hostPath:
          path: /etc/localtime
          type: File
