name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on:ubuntu-latest
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v3
    #
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3

    - name: Log into Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      
    - name: Build and Push Docker Image
      run: |
        docker builx create --use
        docker buildx build --platform linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/stefanportfolio:latest --push .
        
    - name: Set up SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        
    - name: Deploy
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          echo "Pulling latest docker image..."
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/stefanportfolio:latest

          echo "Stopping old container..."
          docker stop portfolio || true
          docker rm portfolio || true

          echo "Starting new container..."
          docker run -d --restart unless-stopped --name portfolio -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/stefanportfolio:latest

          echo "Deployment complete!"
        EOF
        
