name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  # build:
  #   name: Build and Push Docker Image
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #
  #     - name: Log into Docker Hub
  #       run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
  #
  #     - name: Build and Push Docker Image
  #       run: |
  #         docker buildx create --use
  #         docker buildx build --platform linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/stefanportfolio:latest --push .

  setup-ssh:
    name: Set up SSH Key
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH directory and add private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa  # Removes potential Windows line endings
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts  # Adds host to known_hosts to prevent prompt
          ls -lah ~/.ssh  # Debugging: Verify SSH key exists
          cat ~/.ssh/id_rsa | wc -l  # Debugging: Check key length
        shell: bash
      - name: Deploy to Raspberry Pi
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            echo "Pulling latest docker image..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/stefanportfolio:latest
            echo "Stopping old container..."
            docker stop portfolio || true
            docker rm portfolio || true
            echo "Starting new container..."
            docker run -d --restart unless-stopped --name portfolio -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/stefanportfolio:latest
            echo "Deployment complete!"
          EOF
  #
  #
  # deploy:
  #   name: Deploy to Raspberry Pi
  #   runs-on: ubuntu-latest
  #   needs: [setup-ssh]
  #   steps:
  #     - name: Deploy to Raspberry Pi
  #       run: |
  #         ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
  #           echo "Pulling latest docker image..."
  #           docker pull ${{ secrets.DOCKERHUB_USERNAME }}/stefanportfolio:latest
  #           echo "Stopping old container..."
  #           docker stop portfolio || true
  #           docker rm portfolio || true
  #           echo "Starting new container..."
  #           docker run -d --restart unless-stopped --name portfolio -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/stefanportfolio:latest
  #           echo "Deployment complete!"
  #         EOF
  #
