name: Deploy Portfolio & Traceroute Backend (SSH Method)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to deploy'
        required: false
        default: 'latest'

env:
  REGISTRY: docker.io
  PORTFOLIO_IMAGE_NAME: stefanmhall/portfolio
  TRACEROUTE_IMAGE_NAME: stefanmhall/traceroute-backend
  NAMESPACE: stefansportfolio

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Extract metadata for portfolio
      id: meta-portfolio
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.PORTFOLIO_IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value=${{ github.event.inputs.image_tag || 'latest' }}

    - name: Build and push portfolio Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        dockerfile: Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta-portfolio.outputs.tags }}
        labels: ${{ steps.meta-portfolio.outputs.labels }}

    - name: Extract metadata for traceroute backend
      id: meta-traceroute
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.TRACEROUTE_IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value=${{ github.event.inputs.image_tag || 'latest' }}

    - name: Build and push traceroute backend Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        dockerfile: Dockerfile.backend
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta-traceroute.outputs.tags }}
        labels: ${{ steps.meta-traceroute.outputs.labels }}

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          #!/bin/bash
          set -e

          cd /home/stefan/Documents/Personal/StefansPortfolio

          # Pull latest changes
          git pull origin main

          # Deploy both portfolio and traceroute backend
          chmod +x k8s/deploy-portfolio-with-cloudflare.sh
          ./k8s/deploy-portfolio-with-cloudflare.sh

          # Verify deployments
          echo "✅ Portfolio app deployed successfully!"
          echo "Portfolio Image: ${{ env.REGISTRY }}/${{ env.PORTFOLIO_IMAGE_NAME }}:latest"
          kubectl get pods -n ${{ env.NAMESPACE }} -l app=portfolio

          echo ""
          echo "✅ Traceroute backend deployed successfully!"
          echo "Traceroute Image: ${{ env.REGISTRY }}/${{ env.TRACEROUTE_IMAGE_NAME }}:latest"
          kubectl get pods -n ${{ env.NAMESPACE }} -l app=traceroute-backend

    - name: Verify deployment
      run: |
        echo "✅ Portfolio & Traceroute Backend deployment completed!"
        echo "Portfolio Image: ${{ env.REGISTRY }}/${{ env.PORTFOLIO_IMAGE_NAME }}:latest"
        echo "Traceroute Image: ${{ env.REGISTRY }}/${{ env.TRACEROUTE_IMAGE_NAME }}:latest"
        echo "Namespace: ${{ env.NAMESPACE }}"
