name: Deploy Portfolio App (SSH Method)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to deploy'
        required: false
        default: 'latest'

env:
  REGISTRY: docker.io
  IMAGE_NAME: stefanmhall/portfolio
  NAMESPACE: hallphotography
  DEPLOYMENT_NAME: portfolio

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value=${{ github.event.inputs.image_tag || 'latest' }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          #!/bin/bash
          set -e
          
          cd /home/stefan/Documents/Personal/StefansPortfolio
          
          # Pull latest changes
          git pull origin main
          
          # Deploy portfolio using the portfolio-specific k8s structure
          chmod +x k8s/deploy-portfolio-with-cloudflare.sh
          ./k8s/deploy-portfolio-with-cloudflare.sh
          
          # Verify deployment
          echo "✅ Portfolio app deployed successfully!"
          echo "Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
          kubectl get pods -n ${{ env.NAMESPACE }} -l app=portfolio

    - name: Verify deployment
      run: |
        echo "✅ Portfolio app deployment completed!"
        echo "Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
        echo "Namespace: ${{ env.NAMESPACE }}"
